// ------------------------------------------------------------------------------
//  <auto-generated>
//      Dieser Code wurde vom Coded UI-Test-Generator generiert.
//      Version: 14.0.0.0
//
//      In dieser Datei sind spezialisierte Klassen definiert, die in einem
//      Coded UI-Test verwendet werden.
//      In dieser Datei können die erforderlichen Anpassungen vorgenommen werden.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace EinsatzErstellenTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Einsatz_Erstellen - Verwenden Sie "Einsatz_ErstellenParams", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Einsatz_Erstellen()
        {
            #region Variable Declarations
            WinListItem uIM120LB2FS16ListItem = this.UIDebugWindow.UIItemWindow.UIElementansichtList.UIM120LB2FS16ListItem;
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UIM120LB2FS16ListItem.UINameEdit;
            WpfButton uINeuButton = this.UIMainWindowWindow.UINeuButton;
            WpfComboBox uIMitarbeiterComboBox = this.UIEinzelAnsichtWindow.UIMitarbeiterComboBox;
            WpfDatePicker uIDatumDatePicker = this.UIEinzelAnsichtWindow.UIDatumDatePicker;
            WpfEdit uIStart_zeitEdit = this.UIEinzelAnsichtWindow.UIStart_zeitEdit;
            WpfEdit uIEnd_zeitEdit = this.UIEinzelAnsichtWindow.UIEnd_zeitEdit;
            WpfButton uISpeichernButton = this.UIEinzelAnsichtWindow.UISpeichernButton;
            #endregion

            // "Alt + p" in "M120-LB2-FS16" Listenelement eingeben
            Keyboard.SendKeys(uIM120LB2FS16ListItem, this.Einsatz_ErstellenParams.UIM120LB2FS16ListItemSendKeys, ModifierKeys.Alt);

            // Doppelklicken "Name" Textfeld
            Mouse.DoubleClick(uINameEdit, new Point(128, 9));

            // Klicken "Neu" Schaltfläche
            Mouse.Click(uINeuButton, new Point(28, 6));

            // "Anton Affolter" in "mitarbeiter" Kombinationsfeld auswählen
            uIMitarbeiterComboBox.SelectedItem = this.Einsatz_ErstellenParams.UIMitarbeiterComboBoxSelectedItem;

            // "06-Jun-2016" in "datum" Datumsauswahl auswählen
            uIDatumDatePicker.DateAsString = this.Einsatz_ErstellenParams.UIDatumDatePickerDateAsString;

            // "08:00" in "start_zeit" Textfeld eingeben
            uIStart_zeitEdit.Text = this.Einsatz_ErstellenParams.UIStart_zeitEditText;

            // "{Tab}" in "start_zeit" Textfeld eingeben
            Keyboard.SendKeys(uIStart_zeitEdit, this.Einsatz_ErstellenParams.UIStart_zeitEditSendKeys, ModifierKeys.None);

            // "15:00" in "end_zeit" Textfeld eingeben
            uIEnd_zeitEdit.Text = this.Einsatz_ErstellenParams.UIEnd_zeitEditText;

            // Klicken "Speichern" Schaltfläche
            Mouse.Click(uISpeichernButton, new Point(56, 8));
        }
        
        /// <summary>
        /// Einsatz_Ueberpruefen - Verwenden Sie "Einsatz_UeberpruefenExpectedValues", um Parameter an diese Methode zu übergeben.
        /// </summary>
        public void Einsatz_Ueberpruefen()
        {
            #region Variable Declarations
            WpfTable uIListen_ansichtTable = this.UIMainWindowWindow.UIUCViewPane.UIListen_ansichtTable;
            #endregion

            // Sicherstellen, dass die Eigenschaft 'RowCount' von "listen_ansicht" Tabelle ist gleich '5'
            Assert.AreEqual(this.Einsatz_UeberpruefenExpectedValues.UIListen_ansichtTableRowCount, uIListen_ansichtTable.RowCount, "Einsatz nicht erstellt");
        }
        
        /// <summary>
        /// Test_Cleanup
        /// </summary>
        public void Test_Cleanup()
        {
            #region Variable Declarations
            WinButton uISchließenButton = this.UIMainWindowWindow1.UISchließenButton;
            #endregion

            // Klicken "Schließen" Schaltfläche
            Mouse.Click(uISchließenButton, new Point(16, 11));
        }
        
        #region Properties
        public virtual Einsatz_ErstellenParams Einsatz_ErstellenParams
        {
            get
            {
                if ((this.mEinsatz_ErstellenParams == null))
                {
                    this.mEinsatz_ErstellenParams = new Einsatz_ErstellenParams();
                }
                return this.mEinsatz_ErstellenParams;
            }
        }
        
        public virtual Einsatz_UeberpruefenExpectedValues Einsatz_UeberpruefenExpectedValues
        {
            get
            {
                if ((this.mEinsatz_UeberpruefenExpectedValues == null))
                {
                    this.mEinsatz_UeberpruefenExpectedValues = new Einsatz_UeberpruefenExpectedValues();
                }
                return this.mEinsatz_UeberpruefenExpectedValues;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        
        public UIEinzelAnsichtWindow UIEinzelAnsichtWindow
        {
            get
            {
                if ((this.mUIEinzelAnsichtWindow == null))
                {
                    this.mUIEinzelAnsichtWindow = new UIEinzelAnsichtWindow();
                }
                return this.mUIEinzelAnsichtWindow;
            }
        }
        
        public UIMainWindowWindow1 UIMainWindowWindow1
        {
            get
            {
                if ((this.mUIMainWindowWindow1 == null))
                {
                    this.mUIMainWindowWindow1 = new UIMainWindowWindow1();
                }
                return this.mUIMainWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private Einsatz_ErstellenParams mEinsatz_ErstellenParams;
        
        private Einsatz_UeberpruefenExpectedValues mEinsatz_UeberpruefenExpectedValues;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        
        private UIEinzelAnsichtWindow mUIEinzelAnsichtWindow;
        
        private UIMainWindowWindow1 mUIMainWindowWindow1;
        #endregion
    }
    
    /// <summary>
    /// An "Einsatz_Erstellen" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class Einsatz_ErstellenParams
    {
        
        #region Fields
        /// <summary>
        /// "Alt + p" in "M120-LB2-FS16" Listenelement eingeben
        /// </summary>
        public string UIM120LB2FS16ListItemSendKeys = "p";
        
        /// <summary>
        /// "Anton Affolter" in "mitarbeiter" Kombinationsfeld auswählen
        /// </summary>
        public string UIMitarbeiterComboBoxSelectedItem = "Anton Affolter";
        
        /// <summary>
        /// "06-Jun-2016" in "datum" Datumsauswahl auswählen
        /// </summary>
        public string UIDatumDatePickerDateAsString = "06-Jun-2016";
        
        /// <summary>
        /// "08:00" in "start_zeit" Textfeld eingeben
        /// </summary>
        public string UIStart_zeitEditText = "08:00";
        
        /// <summary>
        /// "{Tab}" in "start_zeit" Textfeld eingeben
        /// </summary>
        public string UIStart_zeitEditSendKeys = "{Tab}";
        
        /// <summary>
        /// "15:00" in "end_zeit" Textfeld eingeben
        /// </summary>
        public string UIEnd_zeitEditText = "15:00";
        #endregion
    }
    
    /// <summary>
    /// An "Einsatz_Ueberpruefen" zu übergebende Parameter
    /// </summary>
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class Einsatz_UeberpruefenExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Sicherstellen, dass die Eigenschaft 'RowCount' von "listen_ansicht" Tabelle ist gleich '5'
        /// </summary>
        public int UIListen_ansichtTableRowCount = 5;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Elementansicht";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIElementansichtList UIElementansichtList
        {
            get
            {
                if ((this.mUIElementansichtList == null))
                {
                    this.mUIElementansichtList = new UIElementansichtList(this);
                }
                return this.mUIElementansichtList;
            }
        }
        
        public UIM120LB2FS16ListItem UIM120LB2FS16ListItem
        {
            get
            {
                if ((this.mUIM120LB2FS16ListItem == null))
                {
                    this.mUIM120LB2FS16ListItem = new UIM120LB2FS16ListItem(this);
                }
                return this.mUIM120LB2FS16ListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIElementansichtList mUIElementansichtList;
        
        private UIM120LB2FS16ListItem mUIM120LB2FS16ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIElementansichtList : WinList
    {
        
        public UIElementansichtList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinList.PropertyNames.Name] = "Elementansicht";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinListItem UIM120LB2FS16ListItem
        {
            get
            {
                if ((this.mUIM120LB2FS16ListItem == null))
                {
                    this.mUIM120LB2FS16ListItem = new WinListItem(this);
                    #region Suchkriterien
                    this.mUIM120LB2FS16ListItem.SearchProperties[WinListItem.PropertyNames.Name] = "M120-LB2-FS16";
                    this.mUIM120LB2FS16ListItem.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIM120LB2FS16ListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIM120LB2FS16ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIM120LB2FS16ListItem : WinListItem
    {
        
        public UIM120LB2FS16ListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WinListItem.PropertyNames.Name] = "M120-LB2-FS16";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Suchkriterien
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UINeuButton
        {
            get
            {
                if ((this.mUINeuButton == null))
                {
                    this.mUINeuButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUINeuButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "einzel_ansicht_neu";
                    this.mUINeuButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUINeuButton;
            }
        }
        
        public UIUCViewPane UIUCViewPane
        {
            get
            {
                if ((this.mUIUCViewPane == null))
                {
                    this.mUIUCViewPane = new UIUCViewPane(this);
                }
                return this.mUIUCViewPane;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUINeuButton;
        
        private UIUCViewPane mUIUCViewPane;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIUCViewPane : WpfPane
    {
        
        public UIUCViewPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Suchkriterien
            this.SearchProperties[WpfPane.PropertyNames.ClassName] = "Uia.ScrollViewer";
            this.SearchProperties[WpfPane.PropertyNames.AutomationId] = "UCView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfTable UIListen_ansichtTable
        {
            get
            {
                if ((this.mUIListen_ansichtTable == null))
                {
                    this.mUIListen_ansichtTable = new WpfTable(this);
                    #region Suchkriterien
                    this.mUIListen_ansichtTable.SearchProperties[WpfTable.PropertyNames.AutomationId] = "listen_ansicht";
                    this.mUIListen_ansichtTable.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIListen_ansichtTable;
            }
        }
        #endregion
        
        #region Fields
        private WpfTable mUIListen_ansichtTable;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIEinzelAnsichtWindow : WpfWindow
    {
        
        public UIEinzelAnsichtWindow()
        {
            #region Suchkriterien
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "EinzelAnsicht";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("EinzelAnsicht");
            #endregion
        }
        
        #region Properties
        public WpfComboBox UIMitarbeiterComboBox
        {
            get
            {
                if ((this.mUIMitarbeiterComboBox == null))
                {
                    this.mUIMitarbeiterComboBox = new WpfComboBox(this);
                    #region Suchkriterien
                    this.mUIMitarbeiterComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "mitarbeiter";
                    this.mUIMitarbeiterComboBox.WindowTitles.Add("EinzelAnsicht");
                    #endregion
                }
                return this.mUIMitarbeiterComboBox;
            }
        }
        
        public WpfDatePicker UIDatumDatePicker
        {
            get
            {
                if ((this.mUIDatumDatePicker == null))
                {
                    this.mUIDatumDatePicker = new WpfDatePicker(this);
                    #region Suchkriterien
                    this.mUIDatumDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "datum";
                    this.mUIDatumDatePicker.WindowTitles.Add("EinzelAnsicht");
                    #endregion
                }
                return this.mUIDatumDatePicker;
            }
        }
        
        public WpfEdit UIStart_zeitEdit
        {
            get
            {
                if ((this.mUIStart_zeitEdit == null))
                {
                    this.mUIStart_zeitEdit = new WpfEdit(this);
                    #region Suchkriterien
                    this.mUIStart_zeitEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "start_zeit";
                    this.mUIStart_zeitEdit.WindowTitles.Add("EinzelAnsicht");
                    #endregion
                }
                return this.mUIStart_zeitEdit;
            }
        }
        
        public WpfEdit UIEnd_zeitEdit
        {
            get
            {
                if ((this.mUIEnd_zeitEdit == null))
                {
                    this.mUIEnd_zeitEdit = new WpfEdit(this);
                    #region Suchkriterien
                    this.mUIEnd_zeitEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "end_zeit";
                    this.mUIEnd_zeitEdit.WindowTitles.Add("EinzelAnsicht");
                    #endregion
                }
                return this.mUIEnd_zeitEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Suchkriterien
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "speichern";
                    this.mUISpeichernButton.WindowTitles.Add("EinzelAnsicht");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfComboBox mUIMitarbeiterComboBox;
        
        private WpfDatePicker mUIDatumDatePicker;
        
        private WpfEdit mUIStart_zeitEdit;
        
        private WpfEdit mUIEnd_zeitEdit;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UI-Test-Generator", "14.0.23107.0")]
    public class UIMainWindowWindow1 : WinWindow
    {
        
        public UIMainWindowWindow1()
        {
            #region Suchkriterien
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WinButton UISchließenButton
        {
            get
            {
                if ((this.mUISchließenButton == null))
                {
                    this.mUISchließenButton = new WinButton(this);
                    #region Suchkriterien
                    this.mUISchließenButton.SearchProperties[WinButton.PropertyNames.Name] = "Schließen";
                    this.mUISchließenButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISchließenButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISchließenButton;
        #endregion
    }
}
